config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :outfits do 
    get :autocomplete_item_name, :on => :collection
  end
  resources :categories
  resources :items 
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root "welcome#index" 
  get "/stats" => "stats#index"
  get "/users/:id/show" => "users#show", as: :user
end

app/models/outfit.rb
class Outfit < ApplicationRecord
  validates :date, presence: true
  has_many :outfit_items
  has_many :items, through: :outfit_items, dependent: :destroy
  accepts_nested_attributes_for :items
  has_attached_file :fitpic, styles: { medium: "400", thumb: "150" }, default_url: "/images/:style/missing.png" 
  validates_attachment_content_type :fitpic, content_type: /\Aimage\/.*\Z/
  belongs_to :user

  def display_date
    self.date.strftime('%A, %B %d, %Y') 
  end

  def self.public
    where("private = ?", false) 
  end

  def self.private
    where("private = ?", true)
  end
end

app/controllers/outfits_controller.rb
class OutfitsController < ApplicationController
  before_action :set_outfit, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  autocomplete :item, :name, :full => true
  load_and_authorize_resource

  # GET /outfits
  # GET /outfits.json
  def index
    @outfits = current_user.outfits
  end

  # GET /outfits/1
  # GET /outfits/1.json
  def show
  end

  # GET /outfits/new
  def new
    @outfit = Outfit.new
  end

  # GET /outfits/1/edit
  def edit
  end

  # POST /outfits
  # POST /outfits.json
  def create
    @outfit = current_user.outfits.build(filtered_params)

    respond_to do |format|
      if @outfit.save
        format.html { redirect_to @outfit, notice: 'Outfit was successfully created.' }
        format.json { render :show, status: :created, location: @outfit }
      else
        format.html { render :new }
        format.json { render json: @outfit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /outfits/1
  # PATCH/PUT /outfits/1.json
  def update
    respond_to do |format|
      if @outfit.update(filtered_params)
        format.html { redirect_to @outfit, notice: 'Outfit was successfully updated.' }
        format.json { render :show, status: :ok, location: @outfit }
      else
        format.html { render :edit }
        format.json { render json: @outfit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /outfits/1
  # DELETE /outfits/1.json
  def destroy
    @outfit.destroy
    respond_to do |format|
      format.html { redirect_to outfits_url, notice: 'Outfit was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_outfit
      @outfit = Outfit.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def outfit_params
      params.require(:outfit).permit(:date, :fitpic, :description, :private, :item_ids => [])
    end

    def filtered_params
      filtered_params = outfit_params
      filtered_params[:date] = Date.strptime(filtered_params[:date], '%m/%d/%Y')
      return filtered_params
    end
end

app/helpers/outfits_helper.rb
module OutfitsHelper
end

app/views/outfits/_form.html.erb
<%= form_for(outfit, multipart: true) do |f| %>
  <% if outfit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(outfit.errors.count, "error") %> prohibited this outfit from being saved:</h2>
      <ul>
        <% outfit.errors.full_messages.each do |message| %>
          <li><%= message %></li>        
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field"> 
    <%= f.label :private %> (Select this box if you want your outfit to be hidden from the public landing page) <br>
    <%= f.check_box :private %> 
  </div> 

  <div class="field">
    <%= f.label :date %>
    <%= f.text_field :date, data: { :provide => 'datepicker'}, value: Date.today.strftime('%m/%d/%Y'), id: 'datepicker' %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <p>Where did you wear this outfit? Thoughts/notes, temperature, etc.</p> 
    <%= f.text_area :description %> 
  </div> 

  <div class="field">
    <%= f.label :add_items_to_your_outfit %>
    <%= f.collection_select(:item_ids, current_user.items, :id, :long_name, {}, {class: 'chosen-select', multiple: true, id: "item_collection_select"}) %> 

  </div>

  <div class="field">
    <p>Add a picture of your outfit: (optional) </p>
    <%= f.file_field :fitpic %>
  </div> 

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/outfits/_outfit.html.erb
<div class="col-sm-4">
  <div class="card border-1 rounded" style="padding: 10px; margin-top: 10px">
    <% if outfit.fitpic.exists? %>
      <%= image_tag outfit.fitpic.url(:thumb), :class => "card-img-top" %>
    <% end %> 
    <div class="card-body">
      <h4 class="card-title" style="margin-top: 10px"><%= outfit.display_date %></h4>
      <%= link_to outfit.user.email, user_path(outfit.user) if outfit.user != current_user %>
      <div><%= outfit.description %></div>
      <div><%= render outfit.items %></div>
      <%= link_to 'Show', outfit, :class => "card-link" %>
      <% if can? :edit, outfit %>
        <%= link_to 'Edit', edit_outfit_path(outfit), :class => "card-link" %>
      <% end %> 
      <% if can? :destroy, outfit %>
        <%= link_to 'Destroy', outfit, method: :delete, data: { confirm: 'Are you sure?' },:class => "card-link" %>
      <% end %> 
    </div>
  </div>
</div>

app/views/outfits/edit.html.erb
<h1>Editing Outfit</h1>

<%= render 'form', outfit: @outfit %>

<%= link_to 'Show', @outfit %> |
<%= link_to 'Back', outfits_path %>

app/views/outfits/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Outfits</h1>
  <%= button_to "Log an outfit", new_outfit_path, method: :get %>

<div class="row">
  <%= render @outfits %>
</div>
<br>

app/views/outfits/new.html.erb
<h1>New Outfit</h1>

<%= render 'form', outfit: @outfit %>
<%= link_to 'Back', outfits_path %>

app/views/outfits/show.html.erb
<div class="row">
  <% if @outfit.fitpic.exists? %> 
    <div class="col-sm-8">
        <%= image_tag @outfit.fitpic.url(:medium) %>
    </div>
  <% end %> 
  <div class="col-sm-4">
    <p>
      <strong>Worn on:</strong>
      <%= @outfit.display_date %>
    </p>

    <p>
      <strong>Description:</strong>
      <%= @outfit.description %>
    </p>

    <p><strong>Items</strong></p>
    <%= render @outfit.items %> 

    <% if can? :edit, @outfit %> 
      <%= link_to 'Edit', edit_outfit_path(@outfit) %> |
    <% end %> 
    <%= link_to 'Outfits', outfits_path %>
  </div>
</div>