config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :outfits do 
    get :autocomplete_item_name, :on => :collection
  end
  resources :categories
  resources :items 
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root "welcome#index" 
  get "/stats" => "stats#index"
  get "/users/:id/show" => "users#show", as: :user
end

app/models/item.rb
class Item < ApplicationRecord
  validates :name, presence: true
  belongs_to :user
  has_many :outfit_items
  has_many :outfits, through: :outfit_items, dependent: :destroy
  has_many :item_categories
  has_many :categories, through: :item_categories, dependent: :destroy
  accepts_nested_attributes_for :categories

  def price=(price_input)
    write_attribute :price, currency_to_number(price_input)
  end

  def long_name
    self.name
  end

  def worn_count
    self.outfits.length
  end

  def cost_per_wear
    if (self.worn_count == nil or self.worn_count == 0)
      if (self.price == nil)
        return 0
      else
        return self.price
      end
    else
      if (self.price == nil)
        return 0 
      else
        return self.price / self.worn_count
      end
    end
  end

  def self.most_worn(num)
    Item.all.sort_by(&:worn_count).reverse.take(num)
  end

  def self.least_worn(num) 
    Item.all.sort_by(&:worn_count).take(num)
  end

  def self.never_worn(num)
    never_worn = []
    Item.all.each do |item| 
      never_worn << item if item.worn_count == 0
    end
    return never_worn.take(num)
  end

  def self.lowest_cost_per_wear(num)
    Item.all.sort_by(&:cost_per_wear).take(num)
  end

  def self.highest_cost_per_wear(num)
    Item.all.sort_by(&:cost_per_wear).reverse.take(num)
  end

  def currency_to_number(currency_value)
    (currency_value.is_a? String) ? currency_value.scan(/[.0-9]/).join.to_d : currency_value
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]
  before_action :set_categories, only: [:show, :edit, :new]
  before_action :authenticate_user!
  load_and_authorize_resource

  # GET /items
  # GET /items.json
  def index
    @items = current_user.items.all
  end

  # GET /items/1
  # GET /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
    @categories = current_user.categories
  end

  # POST /items
  # POST /items.json
  def create
    @item = current_user.items.build(item_params) 

    respond_to do |format|
      if @item.save
        format.html { redirect_to items_url, notice: "Item was successfully created." }
        format.json { render :index, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to items_url, notice: 'Item was successfully updated.' }
        format.json { render :index, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    def set_categories
      @categories = current_user.categories
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:name, :brand, :color, :price, :category_ids => [])
    end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<%= form_for(item) do |f| %>
  <% if item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name, class: "required" %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :brand %>
    <%= f.text_field :brand %>
  </div>

  <div class="field">
    <%= f.label :color %>
    <%= f.text_field :color %>
  </div>

  <div class="field">
    <%= f.label :price %>
    <%= f.text_field :price %>
  </div>

  <div class="field">
    <%= f.label :categories %></br>
    <% if !(@categories.length == 0) %> 
      <%= f.collection_check_boxes :category_ids, @categories, :id, :name, :include_hidden => false %>
    <% else %> 
      <p>Create some categories in the Categories page!</p>
    <% end %> 
  </div> 

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/items/_item.html.erb
<p>
  <%= link_to item.name, item_path(item) %>
</p>

app/views/items/edit.html.erb
<h1>Editing Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<h1>Items</h1>

<%= button_to "Add an item", new_item_path, method: 'get' %> 

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Brand</th>
      <th>Color</th> 
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @items.each do |item| %>
      <tr>
        <td><%= item.long_name %></td>
        <td><%= item.brand %></td>
        <td><%= item.color %></td>

        <td><%= link_to 'Show', item %></td>
        <td><%= link_to 'Edit', edit_item_path(item) %></td>
        <td><%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Item', new_item_path %>

app/views/items/new.html.erb
<h1>New Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Back', items_path %>

app/views/items/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @item.long_name %>
</p>

<p>
  <strong>Price: </strong>
  <%= number_to_currency(@item.price) %>
</p>

<p>
  <strong>Brand:</strong>
  <%= @item.brand %>
</p>

<p>
  <strong>Color:</strong>
  <%= @item.color %>
</p>

<p><strong>Worn on:</strong></p>
<div class="row">
  <%= render @item.outfits %>
</div>

<% if @item.categories.length > 0 %> 
  <p>
    <strong>Categories:</strong>
    <% @item.categories.each do |category| %> 
      <%= link_to category.name, category_path(category) %>
    <% end %> 
  </p>
<% end %> 

<%= link_to 'Edit', edit_item_path(@item) %> |
<%= link_to 'Back', items_path %>