config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :outfits do 
    get :autocomplete_item_name, :on => :collection
  end
  resources :categories
  resources :items 
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root "welcome#index" 
  get "/stats" => "stats#index"
  get "/users/:id/show" => "users#show", as: :user
end

app/views/layouts/_flash_messages.html.erb
<div class="container" id="flash_messages">
  <% flash.each do |key, value| %>
    <div class="alert alert-<%= key %> fade in widget-inner">
      <button type="button" class="close" data-dismiss="alert">×</button>
      <%= value %>
    </div>
  <% end %>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle main-nav" data-toggle="collapse" data-target="#navbarCollapse">
        <span class="icon-bar black"></span>
        <span class="icon-bar black"></span>
        <span class="icon-bar black"></span>
      </button>
      <a class="navbar-brand" href="/">outfitLog</a>
    </div>

    <div class="collapse navbar-collapse" id="navbarCollapse">
      <ul class="nav navbar-nav navbar-left">
        <li class=<%= current_page?(items_path) ? "active" : ""%>><%= link_to "Items", items_path %></li>
        <li class=<%= current_page?(categories_path) ? "active" : ""%>><%= link_to "Categories", categories_path %></li>
        <li class=<%= current_page?(outfits_path) ? "active" : ""%>><%= link_to "Outfits", outfits_path %> 
        <li class=""><%= link_to "Stats", stats_path %> 
      </ul>
      
      <ul class="nav navbar-nav navbar-right">
        <li class="nav navbar-nav dropdown"> 
          <% if user_signed_in? %>
            <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= current_user.email %> <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", user_path(current_user) %></li>
              <li><%= link_to "Log Out", destroy_user_session_path, method: :delete %></li>
            </ul>     
          <% else %> 
            <li><%= link_to "Sign up", new_user_registration_path %></li>
            <li><%= link_to "Log in", new_user_session_path %></li>
          <% end %> 
        </li> 
      </ul>
    </div><!-- collapse --> 
  </div><!-- container-fluid --> 
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Outfit Log</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <%#= stylesheet_link_tag href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.2/css/bootstrap.min.css" %>
  </head>

  <body>
    <%= render "layouts/header" %> 

    <div class="container">
      <!-- flash_messages --> 
      <%= flash_messages %> 

      <%= yield %>
    </div>
  </body>
</html>